version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - cmake
    - g++
  python:

    version: 3.7

    install:

      - requirements: source/requirements.txt

sphinx:

  configuration:  source/conf.py

formats: all